# conf/config.yaml
# 默认为True, 控制台打印消息
debug: True

# 日志保留天数
log_days: 3

# 指定进程数
process_num: 4

# 宠汪汪进程数
joy_process_num: 1

jd_cookies:
  - pt_key=AAJhVXlIADATRFvLbUiMLtAfYHu0eZzLL52m1edzSTwPTM1fjNDRu2hKO_OMZCWYLXI0KlJ6f0I;pt_pin=s3232189260603001;
  - pt_key=AAJhVZe3ADDTWBU23PXTS-VfaDrDxMMNl2O7HEkrGQzbq6H9Yr0CQElYJscTemlebYOTyCoE8gA;pt_pin=jessica%E8%8A%B1%E7%8C%AB;
  - pt_key=AAJhVZbfADA4hGmdgGJoIpxsLjknTdyRMUIh0JcX8QkVnJZMt2nq7MxOJ6jdNVMMBC-VD1_nk28;pt_pin=jd_TmQfONZfTXHL;
  - pt_key=AAJhbSZ5ADB9zl7CDyJrIisv8x_4O1QAeoUd99xoyJ_KZOjuSpeGDUQ1Nv9VvrO6HERIvhOCioI;pt_pin=jd_tehHoUaNmjVC;
# 东东农场是否使用水滴换豆卡, 100水滴换20京豆
jd_farm_bean_card: false

# 东东农场每天保留多少水滴, 用于明天的十次浇水任务
jd_farm_retain_water: 80

# 消息通知
notify:
  # TG机器人Token
  tg_bot_token: aaa
  # TG用户ID
  tg_user_id: bbb
  push_plus_token: null

  # push+ group 一对多推送才需要次配置
  push_plus_group: null

  # 依次填上corpid的值,corpsecret的值,touser的值,agentid,media_id的值，注意用,号隔开。
  qywx_am: wwab6977f55a7f34e8,PPYFMFlJMHzymbfs7HNLUU8QFX_mhHxSFxp_ae0VF80,@all,1000003,2wlmnQvA6lxce6OPMNQhGB-Z_TXmBT9lGhCePQzuHCKSq2w9kAjswJSiANClAXDHH

# 在此列表中的脚本, 将不会加入到定时任务中, 如需立即生效, 请手动执行命令: docker-entrypoint
crontab_exclude_scripts:
  #- jd_bean_indiana.py
